name: Deploy to OVH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-bestoffmusic
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # ⚠️ Assure-toi que ton script génère bien les fichiers dans public/
      # ex: public/sitemap.xml et public/sitemap-images.xml
      - name: Generate sitemaps
        env:
          BASE_URL: https://bestoffmusic.fr
        run: npm run sitemap

      - name: Build site with Vite
        env:
          NODE_ENV: production
        run: npm run build

      - name: Deploy to OVH via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: dist/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/.github/**
